apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash, check_password_hash
import enum
from datetime import datetime


class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4


class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100), primary_key=True, default=shortuuid.uuid)
    telephone = db.Column(db.String(11), nullable=False, unique=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum), default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, *args, **kwargs):
        if 'password' in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(FrontUser, self).__init__(*args,**kwargs)

    # 加密 解密
    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self, rawpwd):
        return check_password_hash(self._password, rawpwd)

apps/front/forms.py
from ..forms import BaseForm
from wtforms import StringField,IntegerField
from wtforms.validators import Regexp, EqualTo, ValidationError,InputRequired
from utils import zlcache


class SignupForm(BaseForm):
    # telephone = StringField(validators=[Regexp(r"1[345789]\d{9}", message='请输入正确格式的手机号码')])
    # cms_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码')])
    # username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名')])
    # # password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.][6,20]", message='请输入正确格式的密码')])
    # password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码')])
    # password2 = StringField(validators=EqualTo('password1', message="两次密码不一致"))
    #
    #
    # graph_captcha = StringField(validators=[Regexp(r"\w{4}", message="请输入正确格式的验证码")])
    telephone = StringField(validators=[Regexp(r"1[3456789]\d{9}", message='请输入正确格式的手机号码！')])
    sms_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码！')])
    username = StringField(validators=[Regexp(r".{2,20}", message='请输入正确格式的用户名！')])
    password1 = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    password2 = StringField(validators=[EqualTo("password1", message='两次输入的密码不一致！')])
    graph_captcha = StringField(validators=[Regexp(r"\w{4}", message='请输入正确格式的短信验证码！')])
    # 验证表单正确 用validate_验证的参数 wtforms 会自动调用方法验证
    def validate_sms_captcha(self, field):
        sms_captcha = field.data
        telephone = self.telephone.data
        sms_captcha_mem = zlcache.get(telephone)
        if not sms_captcha_mem and sms_captcha_mem.lower() != sms_captcha.lower:
            raise ValidationError(message='短信验证错误')

    def validate_graph_captcha(self, field):

        # 数据库存储形式  key:graph_captcha  value:graph_captcha
        graph_captcha = field.data
        graph_captcha_mem = zlcache.get(graph_captcha.lower())
        if not graph_captcha_mem:
            raise ValidationError(message='图形验证码错误')

class SigninForm(BaseForm):
    telephone = StringField(validators=[Regexp(r"1[3456789]\d{9}", message='请输入正确格式的手机号码！')])
    password = StringField(validators=[Regexp(r"[0-9a-zA-Z_\.]{6,20}", message='请输入正确格式的密码！')])
    remember=StringField()

class AddPostForm(BaseForm):
    title=StringField(validators=[InputRequired(message='请输入标题')])
    content=StringField(validators=[InputRequired(message='请输入内容')])
    board_id=IntegerField(validators=[InputRequired(message='请输入板块')])


class AddCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入评论内容！')])
    post_id = IntegerField(validators=[InputRequired(message='请输入帖子id！')])

apps/common/views.py
from io import BytesIO

from flask import Blueprint, request, make_response
from utils import restful,zlcache
from exts import alidayu
from utils.captcha import Captcha
from .forms import SmsCaptchaForm

bp = Blueprint("common", __name__, url_prefix='/common')  # 域名

'''旧版本 发送短信'''


# @bp.route('/sms_captcha/')
# def sms_captcha():
#     # /?telephone=xxx
#     # /c/sms_captcha/xxx
#     # 加密短信端口 防止被攻击
#     telephone = request.args.get('telephone')
#     if not telephone:
#         return restful.params_error(message='请输入手机号码')
#     captcha=Captcha.gene_text(number=4)
#     if alidayu.send_sms(telephone,code=captcha):
#         return restful.success()
#     else:
#         # 测试是否成功发送短信
#         # return restful.params_error(message='短信发送失败')
#         return restful.success()

'''短信验证码验证'''
@bp.route('/sms_captcha/', methods=['POST'])
def sms_captcha():
    # /?telephone=xxx
    # /c/sms_captcha/xxx
    # 加密短信端口 防止被攻击
    form = SmsCaptchaForm(request.form)
    if form.validate():
        telephone = form.telephone.data
        captcha = Captcha.gene_text(number=4)
        print('message',captcha)
        if alidayu.send_sms(telephone, code=captcha):
            zlcache.set(telephone,captcha)
            return restful.success()
        else:
            # 正式显示error
            # return restful.params_error()
            zlcache.set(telephone,captcha)
            return restful.success()
    else:
        return restful.params_error(message='参数错误')

'''图形验证码'''
@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    zlcache.set(text.lower(),text.lower())
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    return resp

apps/front/__init__.py
from .views import bp
from . import hooks

apps/front/views.py
from flask import Blueprint, views, render_template, request, make_response, session, url_for, g,abort
from io import BytesIO
from utils.captcha import Captcha
from .forms import SignupForm, SigninForm, AddPostForm,AddCommentForm
from utils import restful, safeutils
from exts import db
from .models import FrontUser
from .decorators import login_required
from ..models import BannerModel, BoardModel, PostModel,CommentModel,HighlightPostModel
import config
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import func

bp = Blueprint("front", __name__, )  # 域名


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    sort=request.args.get('st',type=int,default=1)
    query_obj=None
    # if sort==1:
    #     query_obj=PostModel.query.order_by(PostModel.desc())
    # elif sort==2:
    #     #精华倒叙
    #     query_obj=db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    # #点赞
    # elif sort==3:
    #     query_obj = PostModel.query.order_by(PostModel.desc())
    # else:
    #     #评论数量
    #     query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()

    # 分页器
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    posts = None
    total = 0
    # if board_id:
    #     posts = query_obj.filter_by(board_id=board_id).slice(start, end)
    #     total = query_obj.filter_by(board_id=board_id).count()
    # else:
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()
    # pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)

    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)

    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort':sort
    }

    return render_template('front/front_index.html', **context)

@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post=PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html',post=post)

# @bp.route('/apost/', methods=["GET", "POST"])
# @login_required
# def apost():
#     if request.method == "GET":
#         boards = BoardModel.query.all()
#
#         return render_template('front/front_apost.html', boards=boards)
#     else:
#         form = AddPostForm(request.form)
#         if form.validate():
#             title = form.title.data
#             content = form.content.data
#             board_id = form.board_id.data
#             board = BoardModel.query.get(board_id)
#             if not board:
#                 return restful.params_error(message='没有这个板块')
#             post = PostModel(title=title, content=content)
#             post.board = board
#             db.session.add(post)
#             db.session.commit()
#             return restful.success()
#         else:
#             return restful.params_error(message=form.get_error())
@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user

            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())

@bp.route('/acomment/',methods=["POST"])
@login_required
def add_comment():
    form=AddCommentForm(request.form)
    if form.validate():
        content=form.content.data
        post_id=form.post_id.data
        post=PostModel.query.get(post_id)
        if post:
            comment=CommentModel(content=content)
            comment.post=post
            comment.author=g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这帖子')
    else:
        return restful.params_error(form.get_error())


class SignupView(views.MethodView):
    def get(self):
        # 注册完成后返回上一层页面
        return_to = request.referrer
        # safeutils防止返回值被劫持
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):

            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())


class SignInView(views.MethodView):
    def get(self):
        return_to = request.referrer
        # safeutils防止返回值被劫持
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):

            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')
        # return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号或密码错误')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SignInView.as_view('signin'))

templates/front/front_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
    页面不存在
</body>
</html>

templates/front/front_apost.html
{#{% extends 'front/front_base.html' %}#}
{##}
{#{% block title %}#}
{#    发布帖子#}
{#{% endblock %}#}
{##}
{#{% block head %}#}
{#    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>#}
{#    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>#}
{#    <script src="{{ static('front/js/front_apost.js') }}"></script>#}
{#    <script src="{{ static('front/js/front_apost.js') }}"></script>#}
{##}
{##}
{##}
{#{% endblock %}#}
{##}
{#{% block body %}#}
{#    <form action="" method="post">#}
{#        <div class="form-group">#}
{#            <div class="input-group">#}
{#                <span class="input-group-addon">标题</span>#}
{#                <input type="text" class="form-control" name="title">#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <div class="input-group">#}
{#                <span class="input-group-addon">板块</span>#}
{#                <select name="board_id" id="" class="form-control">#}
{#                    {% for board in boards %}#}
{#                        <option value="{{board.id}}">{{board.name}}</option>#}
{#                    {% endfor %}#}
{##}
{#                </select>#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <script id="editor" type="text/plain" style="height: 400px"></script>#}
{#        </div>#}
{#        <div class="form-group">#}
{#            <script class="btn btn-danger" id="submit-btn">发布帖子</script>#}
{#        </div>#}
{#    </form>#}
{#{% endblock %}#}
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static("front/js/front_apost.js") }}"></script>
{% endblock %}

{% block body %}
<form action="" method="post">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">标题</span>
            <input type="text" class="form-control" name="title">
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon">板块</span>
            <select name="board_id" class="form-control">
                {% for board in boards %}
                    <option value="{{ board.id }}">{{ board.name }}</option>
                {% endfor %}

            </select>
        </div>
    </div>
    <div class="form-group">
        <script id="editor" type="text/plain" style="height:500px;"></script>
    </div>
    <div class="form-group">
        <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
</form>
{% endblock %}

templates/front/front_index.html
{% extends "front/front_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}知了课堂Python论坛{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static("front/css/front_index.css") }}">
{% endblock %}

{% block body %}
{#    <div class="lg-container">#}
{#        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">#}
{#            <!-- 指示器 -->#}
{#            <ol class="carousel-indicators">#}
{#                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>#}
{#                <li data-target="#carousel-example-generic" data-slide-to="1"></li>#}
{#                <li data-target="#carousel-example-generic" data-slide-to="2"></li>#}
{#                <li data-target="#carousel-example-generic" data-slide-to="3"></li>#}
{#            </ol>#}
{##}
{#            <!-- 轮播图 -->#}
{#            <div class="carousel-inner" role="listbox">#}
{#                {% for banner in banners %}#}
{#                    {% if loop.first %}#}
{#                        <div class="item active">#}
{#                    {% else %}#}
{#                        <div class="item">#}
{#                    {% endif %}#}
{#                <a href="{{ banner.link_url }}">#}
{#                    <img src="{{ banner.image_url }}" alt="...">#}
{#                </a>#}
{#                </div>#}
{#                {% endfor %}#}
{#                </div>#}
{##}
{#                <!-- 左右切换的控制按钮 -->#}
{#                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">#}
{#                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>#}
{#                    <span class="sr-only">Previous</span>#}
{#                </a>#}
{#                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">#}
{#                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>#}
{#                    <span class="sr-only">Next</span>#}
{#                </a>#}
{#            </div>#}
{#            <div class="post-group">#}
{#                <ul class="post-group-head">#}
{#                    <li><a href="">最新</a></li>#}
{#                    <li><a href="">精华</a></li>#}
{#                    <li><a href="">点赞最多</a></li>#}
{#                    <li><a href="">评论最多</a></li>#}
{#                </ul>#}
{#                <ul class="post-list-group">#}
{#                    {% for post in posts %}#}
{#                        <li>#}
{#                            <div class="author-avatar-group">#}
{#                                <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}"#}
{#                                     alt="">#}
{#                                <div class="post-info-group">#}
{#                                    <p class="post-title"> {{ post.title }}</p>#}
{#                                    <p class="post-info"><span>作者:{{ post.author.username }}</span>#}
{#                                        <span>发表时间:{{ post.create_time }}</span></p>#}
{#                                    <span>评论:0</span>#}
{#                                    <span>阅读:0</span>#}
{#                                </div>#}
{#                            </div>#}
{#                        </li>#}
{#                    {% endfor %}#}
{#                </ul>#}
{#                <div style="text-align:center;">#}
{#                    {{ pagination.links }}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="sm-container">#}
{#            <div style="padding-bottom:10px;">#}
{#                <a href="{{ url_for ('front.apost') }}" class="btn btn-warning btn-block">发布帖子</a>#}
{#            </div>#}
{#            <div class="list-group" style="padding-bottom: 10px">#}
{#                {% if current_board %}#}
{#                    <a href="/" class="list-group-item">所有板块</a>#}
{#                {% else %}#}
{#                    <a href="/" class="list-group-item active">所有板块</a>#}
{#                {% endif %}#}
{#                {% for board in boards %}#}
{#                    {% if board.id ==current_board %}#}
{#                        <a href="{{ url_for('front.index',bd=board.id) }}"#}
{#                           class="list-group-item active">{{ board.name }}</a>#}
{#                    {% else %}#}
{#                        <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item">{{ board.name }}</a>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <div class="lg-container">
        <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
          <!-- 指示器 -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>

          <!-- 轮播图 -->
          <div class="carousel-inner" role="listbox">
              {% for banner in banners %}
                  {% if loop.first %}
                    <div class="item active">
                  {% else %}
                      <div class="item">
                  {% endif %}
                    <a href="{{ banner.link_url }}">
                        <img src="{{ banner.image_url }}" alt="...">
                    </a>
                </div>
              {% endfor %}
          </div>

          <!-- 左右切换的控制按钮 -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <div class="post-group">
            <ul class="post-group-head">
                {% if current_sort == 1 %}
                    <li class="active"><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=1,bd=current_board) }}">最新</a></li>
                {% endif %}
                {% if current_sort == 2 %}
                    <li class="active"><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=2,bd=current_board) }}">精华帖子</a></li>
                {% endif %}
                {% if current_sort == 3 %}
                    <li class="active"><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=3,bd=current_board) }}">点赞最多</a></li>
                {% endif %}
                {% if current_sort == 4 %}
                    <li class="active"><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                {% else %}
                    <li><a href="{{ url_for("front.index",st=4,bd=current_board) }}">评论最多</a></li>
                {% endif %}
            </ul>
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="author-avatar-group">
                            <img src="{{ post.author.avatar or url_for('static',filename='common/images/logo.png') }}" alt="">
                        </div>
                        <div class="post-info-group">
                            <p class="post-title">
                                <a href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a>
                                {% if post.highlight %}
                                    <span class="label label-danger">精华帖</span>
                                {% endif %}
                            </p>
                            <p class="post-info">
                                <span>作者:{{ post.author.username }}</span>
                                <span>发表时间:{{ post.create_time }}</span>
                                <span>评论:0</span>
                                <span>阅读:0</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div style="text-align:center;">
                {{ pagination.links }}
            </div>
        </div>
    </div>
    <div class="sm-container">
        <div style="padding-bottom:10px;">
            <a href="{{ url_for("front.apost") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
          {% for board in boards %}
              {% if board.id == current_board %}
                  <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
              {% else %}
                  <a href="{{ url_for("front.index",bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
              {% endif %}
          {% endfor %}
        </div>
    </div>
{% endblock %}

templates/front/front_signbase.html
{#{% from 'common/_macros.html' import static%}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.min.js"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>
    <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">
    <script src="{{ static("common/sweetalert/sweetalert.min.js") }}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js") }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signbase.css') }}">
    {% block head %}

    {% endblock %}
</head>
<body>
<div class="outer-box">
    <div class="logo-box">
        <a href="/">

            <img src="{{ url_for('static',filename='common/images/logo.png') }}">
            {#                <img src="{{ static('common/images/logo.png') }}" alt="">#}
        </a>
    </div>
    <h2 class="page-title">
        {% block h2_block %}{% endblock %}
    </h2>
    <div class="sign-box">
        {% block signbox %}{% endblock %}
    </div>
    <span style="display:none;" id="return-to-span">{{ return_to }}</span>
</div>
</body>
</html>

templates/front/front_signup.html
{% extends 'front/front_signbase.html' %}
{% from 'common/_macros.html' import static%}

{% block title %}
    知了课堂注册
{% endblock %}

{% block head %}
    <script src="{{ static('front/js/front_signup.js') }}"></script>
{% endblock %}

{% block h2_block %}
    知了课堂账号注册
{% endblock %}

{% block signbox %}
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
            <span class="input-group-btn">
                <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
            </span>
        </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>
    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">
            </span>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>
{% endblock %}