apps/cms/__init__.py
from .views import bp
# 从主文件夹位置开始导入
import apps.cms.hooks

apps/cms/views.py
import string
import random

from flask import Blueprint, views, render_template, request, session, redirect, url_for, g, jsonify
from .forms import LoginForm, ResetpwdForm, ResetEmailForm, AddBannerForm, UpdateBannnerForm, AddBoardForm, \
    UpdateBoardForm
from .models import CmsUser, CmsPermission
from .decorators import login_required, permission_required
import config
from exts import db, mail
from utils import restful, zlcache
from flask_mail import Message
from apps.models import BannerModel, BoardModel,PostModel,HighlightPostModel

# 注册时 url_prefix 要加/
bp = Blueprint("cms", __name__, url_prefix='/cms')  # 域名


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')


@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/email/')
def email():
    message = Message('邮件发送', recipients=['987639797@qq.com'], body='test')
    mail.send(message)
    return 'success'


@bp.route('/email_captcha/')
@login_required
def email_captcha():
    # memch
    user = g.cms_user
    print(user)
    email = request.args.get('email')

    if not email:
        return restful.params_error('请传递邮箱参数')
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))
    # source.extend(['0','1','2','3','4','5','6','7','8','9'])
    captcha = "".join(random.sample(source, 6))  # 获取验证码,返回的是列表
    # send email

    message = Message('Python BBs', recipients=[email], body='验证码为:%s' % captcha)
    try:
        mail.send(message)
    except:
        return restful.server_error()
    # 验证码 邮箱 存储到memcache
    zlcache.set(email, captcha)
    return restful.success()


@bp.route('/banners/')
@login_required
def banners():
    banners = BannerModel.query.all()
    return render_template('cms/cms_banners.html', banners=banners)


@bp.route('/abanner/', methods=['POST'])
def abanner():
    form = AddBannerForm(request.form)
    if form.validate():
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel(name=name, image_url=image_url, link_url=link_url, priority=priority)
        db.session.add(banner)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/ubanner/', methods=["POST"])
def ubanner():
    form = UpdateBannnerForm(request.form)
    if form.validate():
        banner_id = form.banner_id.data
        name = form.name.data
        image_url = form.image_url.data
        link_url = form.link_url.data
        priority = form.priority.data
        banner = BannerModel.query.get(banner_id)
        if banner:
            banner.name = name
            banner.image_url = image_url
            banner.link_url = link_url
            banner.priority = priority
            print(banner.image_url)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='五轮播图')
    else:
        return restful.params_error(message=form.get_error())


@bp.route('/dbanner/', methods=['POST'])
@login_required
def dbanner():
    banner_id = request.form.get('banner_id')
    if not banner_id:
        return restful.params_error(message="请输入轮播图id")
    banner = BannerModel.query.get(banner_id)
    if not banner:
        return restful.params_error(message='没有这个id')

    db.session.delete(banner)
    db.session.commit()
    return restful.success()


@bp.route('/comments/')
@login_required
@permission_required(CmsPermission.COMMENTER)
def comments():
    return render_template('cms/cms_comments.html')


@bp.route('/posts/')
@login_required
@permission_required(CmsPermission.POSTER)
def posts():
    post_list = PostModel.query.all()
    return render_template('cms/cms_posts.html',posts=post_list)

@bp.route('/boards/')
@login_required
@permission_required(CmsPermission.BORARDER)
def boards():
    board_models = BoardModel.query.all()
    context = {
        'boards': board_models
    }
    return render_template('cms/cms_boards.html', **context)


@bp.route('/aboard/', methods=["POST"])
@login_required
@permission_required(CmsPermission.BORARDER)
def aboard():
    form = AddBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board = BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return restful.success()
    else:
        return restful.params_error(message=form.get_error())


# 修改板块
@bp.route('/uboard/', methods=["POST"])
@login_required
@permission_required(CmsPermission.BORARDER)
def uboard():
    form = UpdateBoardForm(request.form)
    if form.validate():
        name = form.name.data
        board_id = form.board_id.data
        board = BoardModel.query.get(board_id)
        if board:
            board.name = name
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message='五次模块')
    else:
        return restful.params_error(form.get_error())


# 删除板块
@bp.route('/dboard/', methods=["POST"])
@login_required
@permission_required(CmsPermission.BORARDER)
def dboard():
    board_id = request.form.get()
    if not board_id:
        return restful.params_error(message='请传入id')
    board = BoardModel.query.get(board_id)
    if not board:
        return restful.params_error(message='没有这个模块')
    db.session.delete(board)
    db.session.commit()
    return restful.success()


#加精
@bp.route('/hpost/',methods=["POST"])
@login_required
@permission_required(CmsPermission.POSTER)
def hpost():
    post_id=request.form.get('post_id')
    if not post_id:
        return restful.params_error('出入id')
    post=PostModel.query.get(post_id)
    if not post:
        return restful.params_error('无此帖子')
    hightlight=HighlightPostModel()
    hightlight.post=post
    db.session.add(hightlight)
    db.session.commit()
    return restful.success()


#取消精品
@bp.route('/uhpost/',methods=["POST"])
@login_required
@permission_required(CmsPermission.POSTER)
def uhpost():
    post_id=request.form.get('post_id')
    if not post_id:
        return restful.params_error('出入id')
    post=PostModel.query.get(post_id)
    if not post:
        return restful.params_error('无此帖子')
    hightlight=HighlightPostModel.query.filter_by(post_id=post_id)

    db.session.delete(hightlight)
    db.session.commit()
    return restful.success()

@bp.route('/frusers/')
@login_required
@permission_required(CmsPermission.FRONTER)
def frusers():
    return render_template('cms/cms_fronuser.html')


@bp.route('/croles/')
@login_required
@permission_required(CmsPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')


@bp.route('/cusers/')
@login_required
@permission_required(CmsPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


class LoginView(views.MethodView):
    def get(self, message=None):
        return render_template('cms/cms_login.html', message=message)

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CmsUser.query.filter_by(email=email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID] = user.id
                if remember:
                    # 设置持久化 (31天)
                    # config 中PERMANENT_SESSION_LIFETIME=Time
                    session.permanent = True
                    # 不管怎样 要加上返回的 那个函数的前缀
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或密码错误')
        else:
            print(form.errors)
            message = form.errors.popitem()[1][0]
            return self.get(message=message)


@bp.route('/profile/')
def profile():
    return render_template('cms/cms_profile.html')


class RestPwdView(views.MethodView):
    decorators = [login_required]

    def get(self):
        return render_template('cms/cms_resetpassword.html')

    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                return restful.success()

            else:
                return restful.params_error("旧密码错误！")
        else:
            # message = form.get_error()
            return restful.params_error(form.get_error())


class ResetEmailView(views.MethodView):
    decorators = [login_required]

    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        # 验证
        form = ResetEmailForm(request.form)
        email = form.email.data
        print('email', email)
        g.cms_user.email = email
        if form.validate():
            email = form.email.data
            print('email', email)
            g.cms_user.email = email
            db.session.commit()
            return restful.success()

        else:
            return restful.params_error(form.get_error())


bp.add_url_rule('/login/', view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/', view_func=RestPwdView.as_view('resetpwd'))
bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))

apps/front/views.py
from flask import Blueprint, views, render_template, request, make_response, session, url_for, g,abort
from io import BytesIO
from utils.captcha import Captcha
from .forms import SignupForm, SigninForm, AddPostForm,AddCommentForm
from utils import restful, safeutils
from exts import db
from .models import FrontUser
from .decorators import login_required
from ..models import BannerModel, BoardModel, PostModel,CommentModel,HighlightPostModel
import config
from flask_paginate import Pagination, get_page_parameter
from sqlalchemy import func

bp = Blueprint("front", __name__, )  # 域名


@bp.route('/')
def index():
    board_id = request.args.get('bd', type=int, default=None)
    sort=request.args.get('st',type=int,default=1)
    query_obj=None
    # if sort==1:
    #     query_obj=PostModel.query.order_by(PostModel.desc())
    # elif sort==2:
    #     #精华倒叙
    #     query_obj=db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(HighlightPostModel.create_time.desc(),PostModel.create_time.desc())
    # #点赞
    # elif sort==3:
    #     query_obj = PostModel.query.order_by(PostModel.desc())
    # else:
    #     #评论数量
    #     query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())
    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        # 按照加精的时间倒叙排序
        query_obj = db.session.query(PostModel).outerjoin(HighlightPostModel).order_by(
            HighlightPostModel.create_time.desc(), PostModel.create_time.desc())
    elif sort == 3:
        # 按照点赞的数量排序
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 4:
        # 按照评论的数量排序
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())

    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()

    # 分页器
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page - 1) * config.PER_PAGE
    end = start + config.PER_PAGE
    posts = None
    total = 0
    # if board_id:
    #     posts = query_obj.filter_by(board_id=board_id).slice(start, end)
    #     total = query_obj.filter_by(board_id=board_id).count()
    # else:
    #     posts = query_obj.slice(start, end)
    #     total = query_obj.count()
    # pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)

    if board_id:
        query_obj = query_obj.filter(PostModel.board_id == board_id)
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    else:
        posts = query_obj.slice(start, end)
        total = query_obj.count()
    pagination = Pagination(bs_version=3, page=page, total=total, outer_window=0, inner_window=2)

    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination': pagination,
        'current_board': board_id,
        'current_sort':sort
    }

    return render_template('front/front_index.html', **context)

@bp.route('/p/<post_id>/')
def post_detail(post_id):
    post=PostModel.query.get(post_id)
    if not post:
        abort(404)
    return render_template('front/front_pdetail.html',post=post)

# @bp.route('/apost/', methods=["GET", "POST"])
# @login_required
# def apost():
#     if request.method == "GET":
#         boards = BoardModel.query.all()
#
#         return render_template('front/front_apost.html', boards=boards)
#     else:
#         form = AddPostForm(request.form)
#         if form.validate():
#             title = form.title.data
#             content = form.content.data
#             board_id = form.board_id.data
#             board = BoardModel.query.get(board_id)
#             if not board:
#                 return restful.params_error(message='没有这个板块')
#             post = PostModel(title=title, content=content)
#             post.board = board
#             db.session.add(post)
#             db.session.commit()
#             return restful.success()
#         else:
#             return restful.params_error(message=form.get_error())
@bp.route('/apost/', methods=['GET', 'POST'])
@login_required
def apost():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template('front/front_apost.html', boards=boards)
    else:
        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return restful.params_error(message='没有这个板块！')
            post = PostModel(title=title, content=content)
            post.board = board
            post.author = g.front_user

            db.session.add(post)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=form.get_error())

@bp.route('/acomment/',methods=["POST"])
@login_required
def add_comment():
    form=AddCommentForm(request.form)
    if form.validate():
        content=form.content.data
        post_id=form.post_id.data
        post=PostModel.query.get(post_id)
        if post:
            comment=CommentModel(content=content)
            comment.post=post
            comment.author=g.front_user
            db.session.add(comment)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error('没有这帖子')
    else:
        return restful.params_error(form.get_error())


class SignupView(views.MethodView):
    def get(self):
        # 注册完成后返回上一层页面
        return_to = request.referrer
        # safeutils防止返回值被劫持
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):

            return render_template('front/front_signup.html', return_to=return_to)
        else:
            return render_template('front/front_signup.html')

    def post(self):
        form = SignupForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            username = form.username.data
            password = form.password1.data
            user = FrontUser(telephone=telephone, username=username, password=password)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            print(form.get_error())
            return restful.params_error(message=form.get_error())


class SignInView(views.MethodView):
    def get(self):
        return_to = request.referrer
        # safeutils防止返回值被劫持
        if return_to and return_to != request.url and return_to != url_for('front.signup') and safeutils.is_safe_url(
                return_to):

            return render_template('front/front_signin.html', return_to=return_to)
        else:
            return render_template('front/front_signin.html')
        # return render_template('front/front_signin.html')

    def post(self):
        form = SigninForm(request.form)
        if form.validate():
            telephone = form.telephone.data
            password = form.password.data
            remember = form.remember.data

            user = FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[config.FRONT_USER_ID] = user.id
                if remember:
                    session.permanent = True
                return restful.success()
            else:
                return restful.params_error(message='手机号或密码错误')
        else:
            return restful.params_error(message=form.get_error())


bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/signin/', view_func=SignInView.as_view('signin'))

templates/cms/cms_banners.html
{% extends "cms/cms_base.html" %}
{% from "common/_macros.html" import static %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ static('common/zlqiniu.js') }}"></script>
    <script src="{{ static('cms/js/banners.js') }}"></script>
    <style>
        .top-box button{
            float: right;
        }
    </style>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>名称</th>
                <th>图片链接</th>
                <th>跳转链接</th>
                <th>优先级</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}" data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}" data-id="{{ banner.id }}">
                    <td>{{ banner.name }}</td>
                    <td><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn-xs edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn-xs delete-banner-btn">删除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

<!-- Modal -->
<div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">轮播图</h4>
      </div>
      <div class="modal-body">
          <form action="" method="post" class="form-horizontal">
              <div class="form-group">
                  <label class="col-sm-2 control-label">名称：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" placeholder="轮播图名称">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">图片：</label>
                  <div class="col-sm-7">
                      <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                  </div>
                  <button class="btn btn-info col-sm-2" id="upload-btn">添加图片</button>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">跳转：</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                  </div>
              </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">权重：</label>
                  <div class="col-sm-10">
                      <input type="number" class="form-control" name="priority" placeholder="优先级">
                  </div>
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cms/cms_base.html
{% from 'common/_macros.html' import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{% block title %}标题{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href={{ static('cms/css/cms_base.css') }}>
    <script src={{ static('cms/js/cms_base.js') }}></script>
    <script src={{ static('common/zlajax.js') }}></script>
    <script type="text/javascript">
        function myfun() {
            var csrftoken = $('meta[name=csrf-token]').attr('content');

            console.log(csrftoken)

        }

        /*用window.onload调用myfun()*/

        // 不要括号
        window.onload = myfun;
    </script>
    <link rel="stylesheet" href="{{ static('common/sweetalert/sweetalert.css') }}">
    <script src="{{ static('common/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ static('common/sweetalert/zlalert.js') }}"></script>
    {% block head %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for ('cms.profile') }}">{{ g.cms_user.username }}</a></li>
                <li><a href={{ url_for('cms.logout') }}>注销</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="查找...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                    </ul>
                </li>

                {% set cms_user=g.cms_user %}
                <li class="nav-group banner-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                {% if cms_user.has_permission(CmsPermission.POSTER ) %}
                    <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CmsPermission.COMMENTER ) %}
                    <li class="comments-manage"><a href="{{ url_for ('cms.comments') }}">评论管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CmsPermission.BORARDER ) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
                {% endif %}


                {% if cms_user.has_permission(CmsPermission.FRONTER ) %}
                    <li class="nav-group user-manage"><a href="{{ url_for ('cms.frusers') }}">前台用户管理</a></li>
                {% endif %}

                {% if cms_user.has_permission(CmsPermission.CMSUSER ) %}
                    {#                    <li class="nav-group user-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>#}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                {% endif %}

                {#                <li class="role-manage"><a href="#">组管理</a></li>#}

                {% if cms_user.is_developer %}
                    {#                    <li class="nav-group user-manage"><a href="#">用户管理</a></li>#}

                    <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                {% endif %}

            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}标题{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}
                    整体内容
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}
{% block title %}
评论管理
{% endblock %}

{% block head %}
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    评论
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}
{% block title %}
cms角色管理
{% endblock %}

{% block head %}
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    cms角色
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}
{% block title %}
cms用户管理
{% endblock %}

{% block head %}
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    cms用户
{% endblock %}

templates/cms/cms_fronuser.html
{% extends 'cms/cms_base.html' %}
{% block title %}
    前端用户管理
{% endblock %}

{% block head %}
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    前端用户
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}
{% block title %}
    CMS 管理
{% endblock %}

{% block page_title %}
    Welcome
{% endblock %}

templates/cms/cms_posts.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import static %}

{% block title %}帖子管理{% endblock %}

{% block head %}
    <script src="{{ static("cms/js/posts.js") }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>标题</th>
                <th>发布时间</th>
                <th>板块</th>
                <th>作者</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
                <tr data-id="{{ post.id }}" data-highlight="{{ 1 if post.highlight else 0 }}">
                    <td><a target="_blank" href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a></td>
                    <td>{{ post.create_time }}</td>
                    <td>{{ post.board.name }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% if post.highlight %}
                            <button class="btn btn-default btn-xs highlight-btn">取消加精</button>
                        {% else %}
                            <button class="btn btn-default btn-xs highlight-btn">加精</button>
                        {% endif %}
                        <button class="btn btn-danger btn-xs">移除</button>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock %}